Profile/desc more
PalFinderTeam/palFinder pull request #175
Opened 2022-03-27 12:45 UTC by TruddyTheDuddi

**What**
I've finished implementing the profile bio. I've added a "Read more" button if the text overflows to actually see all of the description (it's not a toggle, once you click "Read more", you cannot collapse it back). I don't think we need this feature anywhere else, but if so, I can try to make a separated class that performs this behavior.

**Extra**
I've quickly cleaned up the profile tests, and changed the USER_ID intent message from DUMMY_USER something to USER_ID.

> **Watch out!** Be careful to refactor the code in case we delete the main activity at some point. Or else code using USER_ID will commit death

2022-03-27 19:01 UTC, atappy approved these changes
All fine, could you maybe move showFull to an util class (may be useful for meetup description)

2022-03-28 13:00 UTC, Gerussi requested changes
Great job :) Just one question about the signature of a specific function

2022-03-28 13:00 UTC, Gerussi commented on app/src/main/java/com/github/palFinderTeam/palfinder/ProfileActivity.kt
> +    fun showFullDesc(view: View?) {
Could you explain the presence of the view parameter?

2022-03-28 14:37 UTC, Gerussi approved these changes

2022-03-28 14:51 UTC, merged